name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          macos: echo "Hi from macos"
          linux: |
            echo "Hi from linux"
            echo "Hi from linux second line"
          windows: echo "Hi from windows"
          windowsShell: cmd
          
      - uses: ./
        with:
          macos: echo "test2"
          linux: echo "test2"
          windows: echo "test2"
          windowsShell: cmd

      - uses: lethek/os-specific-run@main
        with:
          macos: echo "Hi from macos"
          linux: |
            echo "Hi from linux"
            echo "Hi from linux second line"
          windows: echo "Hi from windows"

      - uses: lethek/os-specific-run@main
        with:
          macos: echo "test2"
          linux: echo "test2"
          windows: echo "test2"
          windowsShell: cmd
